language: go

go:
  - "1.8"
  - "1.10.x"
  - "1.11.x"
  - master

os:
  - linux
  - osx

install: true

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - env GO111MODULE=on go vet
